### ISSUE TITLE
定时器 你真的会使用吗？ - GrassDog的博客 | GD Blog

### ISSUE THREAD

**Issue by Echo-Evans** [Echo-Evans/Echo-Evans.github.io#1]
http://grassdog.top/2016/12/13/%E6%88%91%E6%9D%A5%E8%AF%95%E8%AF%95%E7%9C%8B%E5%8F%91%E7%82%B9%E4%BB%80%E4%B9%88/ 

 一只前端小草狗流下了没技术的泪水。

**Comment by shengxiaoan** [comment]
测试一哈子
